---
title: "Social Control - Final Models"
author: "Pascal Küng, MSc, Patrick Höhener, MSc, James M. Allen, PhD, Robert Tobias, PhD, Urte Scholz, PhD"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    theme: flatly
    df_print: kable
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: true
    code_folding: show
    toc_depth: 5
    highlight: tango
---

```{r setup, message=FALSE, results='hide'}

knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

#cmdstanr::set_cmdstan_path(path = "C:/Users/kueng/.cmdstan/cmdstan-2.35.0")
#cmdstanr::set_cmdstan_path(path = "C:/Users/pascku/.cmdstan/cmdstan-2.36.0")

library(tidyverse)
library(R.utils)
library(wbCorr)
library(readxl)
library(kableExtra)
library(brms)
library(bayesplot)
library(see)
library(beepr)
library(DHARMa)
library(digest)



source(file.path('Functions', 'ReportModels.R'))
source(file.path('Functions', 'PrettyTables.R'))
source(file.path('Functions', 'ReportMeasures.R'))
source(file.path('Functions', 'PrepareData.R'))

report_function_hash <- digest::digest(summarize_brms)



```


```{r set_options}

system("shutdown /a")

# Set options for analysis
use_mi = FALSE
shutdown = FALSE
report_ordinal = FALSE
do_priorsense = FALSE
get_bayesfactor = F
check_models = T

if (get_bayesfactor) {
  stats_to_report <- c('CI', 'SE', 'pd', 'ROPE', 'BF', 'Rhat', 'ESS')
} else {
  stats_to_report <- c('CI', 'SE', 'pd', 'ROPE', 'Rhat', 'ESS')
}

options(
  dplyr.print_max = 100, 
  brms.backend = 'cmdstan',
  brms.file_refit = ifelse(use_mi, 'never', 'on_change'),
  brms.file_refit = 'on_change',
  #brms.file_refit = 'always',
  error = function() {
    beepr::beep(sound = 5)
    if (shutdown) {
      system("shutdown /s /t 180")
      quit(save = "no", status = 1)
    }
  }
  , es.use_symbols = TRUE
)


####################### Model parameters #######################

iterations = 12000 # 12'000 per chain to achieve 40'000
warmup = 2000 # 2000

# NO AR!!!
#corstr = 'ar'
#corstr = 'cosy_couple'
#corstr = 'cosy_couple:user'


################################################################

suffix = paste0('_MainModels_3_level_LATENT', as.character(iterations))


```


```{r prepare_datasets, results='asis'}

df <- openxlsx::read.xlsx(file.path('long.xlsx'))
df_original <- df

df_double <- prepare_data(df, recode_pushing = TRUE, use_mi = use_mi)[[1]]
summary(df_double$pushing)

```

# Prepare latent stuff

```{r}

df_double <- df_double %>%
  rename(
    received_persuasion_self = persuasion_self,
    received_persuasion_partner = persuasion_partner,
    received_persuasion_self_cw = persuasion_self_cw,
    received_persuasion_partner_cw = persuasion_partner_cw,
    received_persuasion_self_cb = persuasion_self_cb,
    received_persuasion_partner_cb = persuasion_partner_cb,
    
    received_pressure_self = pressure_self,
    received_pressure_partner = pressure_partner,
    received_pressure_self_cw = pressure_self_cw,
    received_pressure_partner_cw = pressure_partner_cw,
    received_pressure_self_cb = pressure_self_cb,
    received_pressure_partner_cb = pressure_partner_cb,
    
    received_pushing_self = pushing_self,
    received_pushing_partner = pushing_partner,
    received_pushing_self_cw = pushing_self_cw,
    received_pushing_partner_cw = pushing_partner_cw,
    received_pushing_self_cb = pushing_self_cb,
    received_pushing_partner_cb = pushing_partner_cb
  )

```




# Correlations between self-report and partner-report

```{r corrs_measures_self_partner, results='asis'}

cors <- wbCorr(
  df_double[,c('exerted_persuasion_self', 'received_persuasion_partner')], 
  df_double$coupleID, 
  method = 'spearman')

summary(cors, 'wb')

cors <- wbCorr(
  df_double[,c('exerted_pressure_self', 'received_pressure_partner')], 
  df_double$coupleID, 
  method = 'spearman')

summary(cors, 'wb')

cors <- wbCorr(
  df_double[,c('exerted_pushing_self', 'received_pushing_partner')], 
  df_double$coupleID, 
  method = 'spearman')

summary(cors, 'wb')
```


# Reliability Omega within-person and between-person 
```{r omegasem, results='asis'}

reliability_psc <- multilevelTools::omegaSEM(
  c('exerted_persuasion_self', 'received_persuasion_partner'),
  'coupleID',
  data = df_double
)

print(reliability_psc)


reliability_nsc <- multilevelTools::omegaSEM(
  c('exerted_pressure_self', 'received_pressure_partner'),
  'coupleID',
  data = df_double
)

print(reliability_nsc)


reliability_pushing <- multilevelTools::omegaSEM(
  c('exerted_pushing_self', 'received_pushing_partner'),
  'coupleID',
  data = df_double
)

print(reliability_pushing)


```


#LATENT STUFF

# Modelling

## Only exerted persuasion. 
```{r}

# add empty latent variable to data frame
df_double$exerted_persuasion <- as.numeric(NA)

# Measurement model
bf1 <- bf(exerted_persuasion_self ~ 0 + mi(exerted_persuasion))
bf2 <- bf(received_persuasion_partner ~ 0 + mi(exerted_persuasion))

bf3 <- bf(exerted_persuasion | mi() ~ 0 + (1 | coupleID))

default_prior(bf1 + bf2 + bf3, data = df_double)

fit <- brm(
  bf1 + bf2 + bf3, 
  data = df_double,
  prior = 
    c(
      prior(normal(1, 1), coef = miexerted_persuasion, resp =exertedpersuasionself),
      prior(normal(1,0.000001), coef = miexerted_persuasion, resp = receivedpersuasionpartner)
    ),
  file = 'testtest',
  family = gaussian(), 
  chains= 4, 
  cores = 4
)

summary(fit)

```





